proyecto1/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :posts
  resources :images
  root 'welcome#index'
end

proyecto1/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

proyecto1/app/models/image.rb
class Image < ApplicationRecord
end

proyecto1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

proyecto1/app/controllers/images_controller.rb
class ImagesController < ApplicationController

    before_action :set_image, only: [:show, :edit, :update, :destroy]

def index
    @images = Image.all            # variable de tipo array @images
end

def new
end

def create
    #render plain: params[:image].inspect
    @image = Image.new images_params
    @image.save
    redirect_to @image  #redirecciona a una nueva vista
end

def show
  
end

def edit
  
end

def update
    @image.update images_params 
    redirect_to @image
end

def destroy
    @image.destroy
    redirect_to images_path 
end

private

def images_params
    params.require(:image).permit(:description)
end 

def set_image
    @image = Image.find params[:id]
end
end

proyecto1/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    def new

    end
end

proyecto1/app/helpers/application_helper.rb
module ApplicationHelper
end

proyecto1/app/helpers/images_helper.rb
module ImagesHelper
end

proyecto1/app/helpers/welcome_helper.rb
module WelcomeHelper
end

proyecto1/app/views/images/_form.html.erb
<%= form_for @image do |f| %>
        <%= f.label 'Descripción' %> <br>
        <%= f.text_field :description %>
        <br>
       
        <%= f.submit 'Lo que sea', :class => 'btn btn-default' %>
 <% end %>

 <div class="form-group"> 
    <%= form_for @image do |f| %>
        <%= f.label :description %> <br>
        <%= f.text_field :description, class: 'form-control' %>
        <br>
        <%= f.submit 'Enviar', :class => 'btn btn-primary' %>
    <% end %>
</div>

proyecto1/app/views/images/_images.html.erb
<%= @image.description %> <br>
<%= link_to 'Editar', edit_image_path(image) %><br>

<%= link_to 'Eliminar', image, method: :delete, data:{ 
    confirm: 'Esta seguro? seguro? segurisimo? de eliminar esta imagen.'  }% >

<div class="col">
    <figure class="figure">
        <img src="https://getuikit.com/v2/docs/images/placeholder_600x400.svg" 		 class="figure-img img-fluid rounded">
        <figcaption class="figure-caption">
            <%= image.description %> 
            <%= link_to 'Editar', edit_image_path(image) %>
            <%= link_to 'Eliminar', image, method: :delete, data:{ 
                    confirm: 'Esta seguro que decea eliminar esta imagen.'
                } %>        
        </figcaption> 
    </figure>
</div>

proyecto1/app/views/images/edit.html.erb
<p>EDITAR IMAGENES</p>
<%= render 'form' %>

proyecto1/app/views/images/index.html.erb
<%= render @images%>

<div class="row">
    <%= render @images %>
</div>
 

proyecto1/app/views/images/new.html.erb
<p>CREAR IMAGENES</p>
<%= render 'form' %>

proyecto1/app/views/images/show.html.erb
<%=@image.description %>

proyecto1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proyecto1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

proyecto1/app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>